[build]
  publish = "neumorphism-todo/build"
  command = "cd neumorphism-todo && npm run build"
  base = "neumorphism-todo"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
